FROM golang:1.20

WORKDIR /app

RUN go install github.com/cosmtrek/air@latest

COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "--build.cmd", "go build -o bin/docmonk.bin ./cmd/docmonk.go", "--build.bin", "./bin/docmonk.bin", "--build.exclude_dir", "frontend,bin,tmp,db"]